id: IA18A09AF
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-14T06:41:09+00:00'
last_modified: '2022-06-10T04:43:28.371202+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG21760
  title: བོད་ཀྱི་སྐར་རྩིས་རིག་པའི་རྣམ་བཞག
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    EC94:
      image_group_id: I1KG21870
      title: Volume 1 of bod kyi skar rtsis rig pa'i rnam bzhag
      total_pages: 518
      order: 1
      base_file: EC94.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
